:bug: Fix thermal HAL compilation
There's no need to defined twice this HAL.
One in manifest.xml and another while using:

PRODUCT_PACKAGES += \
	android.hardware.thermal@2.0-service.mock

This was the error:

FAILED: Verifying vendor VINTF manifest.
Outputs: out/target/product/santoni/verified_assembled_vendor_manifest.xml
Error: exited with code: 1
Command: /bin/bash -c "PRODUCT_ENFORCE_VINTF_MANIFEST=true              out/host/linux-x86/bin/assemble_vintf               -c out/target/product/santoni/obj/ETC/verified_assembled_system_matrix.xml_intermediates/verified_assembled_system_matrix.xml            -i out/target/product/santoni/obj/ETC/device_manifest.xml_intermediates/manifest.xml            \$([ -d out/target/product/santoni/vendor/etc/vintf/manifest ] &&            find out/target/product/santoni/vendor/etc/vintf/manifest -type f -name \"*.xml\" |             sed \"s/^/-i /\" | tr '\\n' ' ') -o out/target/product/santoni/verified_assembled_vendor_manifest.xml"
Output:
File "out/target/product/santoni/vendor/etc/vintf/manifest/android.hardware.thermal@2.0-service.xml" cannot be added: HAL "android.hardware.thermal" has a conflict.