:bug: Fix selinux and manifest conflicts
After cleaning the "out" dir I got this problem:

FAILED: out/target/product/santoni/obj/ETC/vendor_file_contexts_intermediates/vendor_file_contexts
/bin/bash -c "(m4 --fatal-warnings -s     system/sepolicy/vendor/file_contexts  out/target/product/santoni/obj/ETC/sectxfile_nl_intermediates/sectxfile_nl    device/qcom/sepolicy/legacy-um/vendor/common/file_contexts  out/target/product/santoni/obj/ETC/sectxfile_nl_intermediates/sectxfile_nl    device/xiaomi/santoni/sepolicy/vendor/file_contexts  out/target/product/santoni/obj/ETC/sectxfile_nl_intermediates/sectxfile_nl    device/pa/sepolicy/qcom/vendor/file_contexts  out/target/product/santoni/obj/ETC/sectxfile_nl_intermediates/sectxfile_nl    device/qcom/sepolicy/legacy-um/vendor/msm8937/file_contexts  out/target/product/santoni/obj/ETC/sectxfile_nl_intermediates/sectxfile_nl    device/pa/sepolicy/common/vendor/file_contexts  out/target/product/santoni/obj/ETC/sectxfile_nl_intermediates/sectxfile_nl > out/target/product/santoni/obj/ETC/vendor_file_contexts_intermediates/vendor_file_contexts.tmp ) && (out/host/linux-x86/bin/checkfc out/target/product/santoni/obj/ETC/sepolicy_intermediates/sepolicy out/target/product/santoni/obj/ETC/vendor_file_contexts_intermediates/vendor_file_contexts.tmp ) && (out/host/linux-x86/bin/fc_sort out/target/product/santoni/obj/ETC/vendor_file_contexts_intermediates/vendor_file_contexts.tmp out/target/product/santoni/obj/ETC/vendor_file_contexts_intermediates/vendor_file_contexts )"
out/target/product/santoni/obj/ETC/vendor_file_contexts_intermediates/vendor_file_contexts.tmp: Multiple same specifications for /(vendor|system/vendor)/bin/hw/android\.hardware\.power@1\.2-service.
Error: could not load context file from out/target/product/santoni/obj/ETC/vendor_file_contexts_intermediates/vendor_file_contexts.tmp

And then another conflict with the manifest.xml hidl declaration for android.hardware.power
Removing them solves the issue (as they're already declared by the build system).